---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-create
  namespace: threeport-control-plane
data:
  db.sql: |+
    CREATE USER IF NOT EXISTS tp_rest_api
      LOGIN
    ;
    CREATE DATABASE IF NOT EXISTS threeport_api
        encoding='utf-8'
    ;
    GRANT ALL ON DATABASE threeport_api TO tp_rest_api;

