---
apiVersion: v1
kind: Secret
metadata:
  name: workload-controller-config
  namespace: threeport-control-plane
type: Opaque
stringData:
  API_SERVER: http://threeport-api-server
  MSG_BROKER_HOST: nats-js
  MSG_BROKER_PORT: "4222"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: threeport-workload-controller
  namespace: threeport-control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: threeport-workload-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: threeport-workload-controller
    spec:
      containers:
      - name: workload-controller
        image: threeport-workload-controller-dev:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: workload-controller-config
        volumeMounts:
        - name: code-path
          mountPath: "/threeport"
      volumes:
      - name: code-path
        hostPath:
          path: /threeport-rest-api
          type: Directory

